Default:
    Baseline: tizen-3.0
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: America/Los_Angeles
    RootPass: tizen
    DefaultUser: tizen
    DefaultUserPass: tizen
    BootloaderOptions: ""



Mobile:
    Bootloader: True
    BootloaderAppend: "rootdelay=5 security=none"
    BootloaderTimeout: 0
    SaveRepos: True
    Desktop: None
    Mic2Options: -f loop --pack-to=@NAME@.zip
    Part: base
    Groups:
        - Base System
        - common
        - appscommon
        - appstargetsdk
        - osp
    Repos:
        - mobile
