Description: Mobile Applications
Name: mobile-applications
Packages:
- org.tizen.app-selector
- org.tizen.bt-syspopup
- org.tizen.indicator
#TODO: Reenable after all packages build
#- org.tizen.lowbat-syspopup
#- org.tizen.lowmem-syspopup
- org.tizen.menu-screen
- org.tizen.net-popup
#- org.tizen.poweroff-syspopup
- org.tizen.pwlock
- org.tizen.taskmgr
- org.tizen.usb-syspopup
- org.tizen.volume
#- org.tizen.wifi-direct-popup
#- org.tizen.wifi-direct-ugapp
- org.tizen.setting
Summary: Mobile Applications
