Summary: Mobile Applications
Description: Mobile Applications
Name: mobile-applications
Packages:
- ca-certificates
- app-installers
- tpk-backend
- wgt-backend
- capi-appfw-app-manager
- starter
- org.tizen.menu-screen
- data-provider-master
- libwidget_service
- libwidget_viewer
- libwidget_viewer_evas
- org.tizen.quickpanel
- org.tizen.volume
- boot-animation
- org.tizen.setting
- org.tizen.setting-location
- org.tizen.myplace
- attach-panel-gallery
- attach-panel-camera
- attach-panel-voicerecorder
- org.tizen.browser
- attach-panel
- org.tizen.app-selector
- org.tizen.callmgr-popup
- org.tizen.heremaps-uc
- org.tizen.download-manager
- my-account
- org.tizen.gps-syspopup
- org.tizen.ode
- org.tizen.dpm-syspopup
- org.tizen.krate-setup-wizard
- org.tizen.voice-setting
- net.netpopup
- org.tizen.powerkey-syspopup
- org.tizen.widget_viewer_sdk
- org.tizen.voice-control-panel
- org.tizen.screen-reader
- org.tizen.crash-syspopup
- org.tizen.system-signal-sender
- org.tizen.system-syspopup
- sticker-panel
- org.tizen.kaskit
- org.tizen.privacy-setting
- org.tizen.keyguard
- org.tizen.overheat-syspopup
- org.tizen.tts-engine-default
- org.tizen.stt-engine-default
