Summary: Mobile Applications
Description: Mobile Applications
Name: mobile-applications
Packages:
- ail
- ca-certificates
- app-installers
- tpk-backend
- wgt-backend
- capi-appfw-app-manager
- starter
- org.tizen.menu-screen
- data-provider-master
- libwidget_service
- libwidget_viewer
- libwidget_viewer_evas
- org.tizen.quickpanel
- org.tizen.lockscreen
- org.tizen.task-mgr
- org.tizen.indicator
- org.tizen.volume
- boot-animation
- org.tizen.setting
- org.tizen.setting-location
- org.tizen.myplace
- org.tizen.myfile
- org.tizen.gallery
- attach-panel-gallery
- ug-gallery-efl
- ug-myfile-efl
- attach-panel-camera
- attach-panel-voicerecorder
- org.tizen.video-player
- org.tizen.videos
- ug-image-viewer-efl
- org.tizen.contacts
- org.tizen.music-chooser
- org.tizen.music-player
- org.tizen.calendar
- org.tizen.call-ui
- org.tizen.call-setting
- org.tizen.message
- org.tizen.setting-notification
- org.tizen.wallpaper-ui-service
- libug-worldclock-efl
- org.tizen.setting-homescreen
- org.tizen.ug-lockscreen-options
- org.tizen.browser
- org.tizen.email
- attach-panel
- org.tizen.camera-app
- org.tizen.app-selector
- org.tizen.share-panel
- org.tizen.homescreen-efl
- org.tizen.callmgr-popup
- org.tizen.heremaps-uc
- org.tizen.download-manager
- my-account
- org.tizen.gps-syspopup
- org.tizen.ode
- org.tizen.dpm-syspopup
- org.tizen.zone-setup-wizard
- org.tizen.voice-setting
- net.netpopup
- org.tizen.poweroff-syspopup
- org.tizen.widget_viewer_sdk
- org.tizen.voice-control-panel
